### ISSUE TITLE
Unencrypted passwords

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices#273]
Found unencrypted passwords in the user table audit log (public.whispersservices_historicaluser) for all accounts created on or after 2/1/2019.

See here:
select *
from public.whispersservices_historicaluser
where password not like 'pbkd%';

**Comment by nbaertlein** [comment]
Thanks Aaron.  Is there anyway to prevent it from happening?  We just had a couple new accounts created and their new passwords are not encrypted.  In looking at the history date, it appears the encryption occurs a fraction of second later.  
See here: 
select * 
from public.whispersservices_historicaluser 
where id in (59,60)
order by id, history_id;

It's buried and probably not a huge deal, but it would be nice to eliminate if we want the system airtight.

**Comment by BlakeDraper** [comment]
@aaronstephenson ☝️

**Comment by aaronstephenson** [comment]
I figured out why this is happening. The usual `create()` method doesn't encrypt the password, but the `set_password()` method that I'm calling after the create does encrypt. So the password is getting saved in plain text with that initial `create()` call but then encrypted with the `set_password()` call. The solution is to just pop the password out of the submitted array before calling `create()`. I'll include this in my next commit.

**Comment by aaronstephenson** [comment]
OK, the code has been updated on the server. I also deleted the offending records from the historicaluser table.
