### ISSUE TITLE
Collaboration Request

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/whispersservices#304]
**Notification Text**
The user [C] has requested to collaborate on event [A].

**Trigger Action**
A collaboration request for a specific event is made.

**Recipients**
event owner, org admin

**Source**
User requesting that they be a collaborator on an event. 

**Email Forwarding**
Automatic, to event owner and organization admin

**Link in WHISPers**
Event Details

**Comment by BlakeDraper** [comment]
For this one, we will need a custom action or an endpoint. User will request to collaborate within WHISPers frontend, then need a place to send the request which should capture the user's details plus a comment. Comment is not saved - only serves the notification.

**Comment by aaronstephenson** [comment]
Implemented in fb628a08

**Comment by BlakeDraper** [comment]
@aaronstephenson what is the endpoint and/or action the client should use for this one?

**Comment by aaronstephenson** [comment]
POST .../events/{id}/request_collaboration/

The body is just plan text (and the Content-Type is `text/plain`), like we've done elsewhere

![image](https://user-images.githubusercontent.com/8713712/71295720-c8173800-2342-11ea-8245-2a2d5577a72b.png)

![image](https://user-images.githubusercontent.com/8713712/71295749-da917180-2342-11ea-926b-d7ff5f42a314.png)

**Comment by aaronstephenson** [comment]
Released in 2.0.0 3111f67
