### ISSUE TITLE
Alert Collaborator

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/whispersservices#306]
**Notification Text**
[C] has created an Alert for Event [A]. Details: [J]. Alert sent to: [K]

**Trigger Action**
A qualified user has triggered a collaborator alert. (The creator of the collaborator alert has the option to choose which of the event collaborators are notified.)

**Recipients**
user(s) chosen from among the collaborator list 

**Source**
A qualified user who creates a collaborator alert. 

**Email Forwarding**
Automatic, to all users included in the notificiation request. 

**Link in WHISPers**
Event Details

**Comment by aaronstephenson** [comment]
Implemented in 0f30b8ac

**Comment by BlakeDraper** [comment]
@aaronstephenson also need to know the submit instructions for this one

**Comment by aaronstephenson** [comment]
POST to .../events/{id}/alert_collaborator/

body is JSON, two fields: `recipients` (list/array or collaborator user IDs, required), `comment` (string, optional)

![image](https://user-images.githubusercontent.com/8713712/71296044-dfa2f080-2343-11ea-84ca-0bb438f80b97.png)

**Comment by aaronstephenson** [comment]
Released in 2.0.0 3111f67
