### ISSUE TITLE
Hosting documentation apps

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#374]
Just starting the discussion - any thought on how we wish to host the API docs and the client code docs (something I am throwing in the mix late because we have it)? Not that I think the answer is complicated - right on the EROS server I imagine. I guess we mainly need to discuss URL paths.

`/api/documentation`
 and maybe `/whispers/codedocs` ?

**Comment by aaronstephenson** [comment]
I planned to put the API docs at `/api/docs/`

I think this is the first I'm hearing about client code docs. What is it?

**Comment by BlakeDraper** [comment]
It uses this package: https://compodoc.app/

To auto-generate documentation of the codebase. Here is a screenshot. 

![image](https://user-images.githubusercontent.com/6978380/80835371-3ce36400-8bb8-11ea-9eae-5081db6b031e.png)


It's pretty neat. You can also run it yourself locally if you do a fresh `git pull` of whispers from dev, run `npm install` and then follow the instructions in the README under Documentation.

**Comment by aaronstephenson** [comment]
Implemented with upgrade to Django REST Framework v3.12 and use of OpenAPI 3 in 2.0.0 3111f67
