### ISSUE TITLE
Require email verification before activating new users

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispersservices#386]
Since WHISPers sends users email notifications, it would be good to verify that the email address entered by the user is correct. Also as a security check, this would verify that the user actually owns the provided email address.

The general flow will be something like this:
- user account is requested like normal
- a secure random string is associated with the new user record. The user record has is_active=False
- an email is sent to the user with a link to click on this. This link is to an email verification URL with the secure random string
- (frontend) a message is displayed to the user, informing them to soon expect an email with a link that they should click on to verify their email address
  - this should be a dialog instead of a toast message so it is more obvious for the user
- when the user clicks on the email verification URL, the secure random string is checked to see if it matches. If it does, the user record is updated to is_active=True
- (frontend) a success message is displayed to the user, informing them that their user account is now active and they may proceed to login (toast message)

Edge cases:
- user tries to login but they haven't verified their email address yet
  - display an error message in the login dialog, displaying the email address
  - ❓ automatically resend the verification email?
- user clicks email verification link but it has expired or otherwise doesn't work
  - resend verification link email
  - display error message to the user instead of the login dialog as would normally be the case if the link did work

Other notes:
- check when Public User email gets sent for a new account. We'll want it to instead only send when the email address is verified and the user account is made active.
- is there already a check for registering with an email address that is already in use?

TODO
- [x] Send 'User Created' email after email address is confirmed and user account is activated
- [x] don't send user change request email until after email address is confirmed and user account is activated
- [x] add `email_verified` to user model
- [x] resend confirmation email if token verification fails
- [x] handle user login when email hasn't yet been confirmed
- [x] move email verification email template to NotificationEmailTemplate

**Comment by machristie** [comment]
Hi @aaronstephenson , I'm working on adding email verification to the user account creation process. A key aspect of that is storing a secure random string that will be used to verify the user's email account (see the issue description above for details).  In looking at the User model I noticed that it has an [active_key](https://github.com/USGS-WiM/whispersservices_django/blob/master/whispersservices/models.py#L1588) field. It appears that this active_key isn't used in the code, but I could be wrong. I wonder if the purpose of this active_key is to hold a secure random string that when verified activates the user account? I ask because the name of the field suggests that and I don't want to add a redundant field if active_key would suit my purposes. Thanks.

**Comment by aaronstephenson** [comment]
It's been years since we established the extra fields on the User model, and I don't remember what `active key` was for. I do know that it's not used anywhere in the code, so I say feel free to use it for verification.

**Comment by machristie** [comment]
Thanks @aaronstephenson

**Comment by machristie** [comment]
Hi @aaronstephenson , another question. Neil mentioned that you're currently working on revamping notifications, so I checked out that branch. Seems like I should send the email with the email verification link as a notification, using `immediate_tasks.generate_notification`, since that seems like the new approach.

Is my understanding on the right path? When I have my code changes ready, should I open a PR against the notifications branch?  Thanks.

**Comment by aaronstephenson** [comment]
Yes, use the `notifications` branch. The `master` branch is hundreds of commits behind and we have completely changed our approach to contacting users.

That said, which of the two functions in immediate_tasks.py you should use depends on what you want to do. Do you want to create a notification and/or an email, or do you want to create only an email? If the latter is the case, then use `immediate_tasks.construct_notification_email` directly.

**Comment by machristie** [comment]
@aaronstephenson I suppose I only want to create an email, but I don't quite understand the difference between an email and a notification. Is the distinction that notifications would display on the User Dashboard? In that case, I suppose there's no need to have a notification since the verification link itself will only be temporarily valid and the user won't see the notification until they verify their email address.

**Comment by aaronstephenson** [comment]
Yes you have it exactly. The notification is only used in the client app.

**Comment by machristie** [comment]
Hi @aaronstephenson . I recently met with Neil to discuss progress on this issue and he asked about the email with the verification link, if it would be configurable. I explained that the way I have it now, the subject and body of the email verification template is hardcoded. Since it's not a notification, it didn't seem appropriate to use the NotificationMessageTemplate. Neil wondered if perhaps the Configuration model could be used instead for the email verification template. Or perhaps there is a better existing option, or a new configurable "email template" model should be created? Any thoughts?  Thanks.

**Comment by aaronstephenson** [comment]
I think it depends on the content of those two fields.

If they are both static text, you can certainly use the Configuration table for this and add two records, one for the subject and one for the body, perhaps with names like `verification_email_subject` and `verification_email_body`.

If either of them requires variable substitution, just use NotificationMessageTemplate. Yes, email verification is not a notification, but the model was designed to work for both notification records and emails, and it seems redundant to create a new model with the exact same fields. If the model name is bothersome if you go this route, you could talk to Neil about changing the model name to something more appropriate.

**Comment by machristie** [comment]
@aaronstephenson thanks, yes, they have variable substitution. I'll use the NotificationMessageTemplate.

**Comment by machristie** [comment]
Hi @aaronstephenson . I have the code commits on a branch I made off of the notifications branch. I'm planning to submit a PR to merge these into the notifications branch. Does that sound good? Thanks.

**Comment by aaronstephenson** [comment]
@machristie yes that sounds good, thanks.

**Comment by machristie** [comment]
This is merged to dev
