### ISSUE TITLE
Create data migration to create expected lookup table records

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispersservices#403]
The code expects that certain records already exist in the database. For example, the code assumes that the following Role records exist:
- SuperAdmin
- Admin
- PartnerAdmin
- PartnerManager
- Partner
- Affiliate
- Public

I've encountered these issues while developing on the code in my local dev environment, where my local database is brand new. While it hasn't been too hard to add these missing records as needed, it does add friction to the development process. It can also lead to a misunderstanding of how the code functions. For example, it wasn't clear to me that users are always assigned the 'Public' Organization when initially created, since I saw during development that new users I created for testing were not assigned an Organization. The problem was that my local dev environment didn't have a 'Public' Organization so [the code that assigns the initial organization was simply not finding the 'Public' Organization](https://github.com/USGS-WiM/whispersservices_django/blob/notifications/whispersservices/serializers.py#L4390).

In addition to Roles, I've found the following records that the code assumes already exist:
- the 'Public' Organization
- the 'Other' CommentType
- [the admin user is assumed to have an id of 1](https://github.com/USGS-WiM/whispersservices_django/blob/notifications/whispersservices/immediate_tasks.py#L105)

And there are probably others.

I would propose that these special lookup records be created by a [data migration](https://docs.djangoproject.com/en/3.0/topics/migrations/#data-migrations). This way when a developer sets up a development environment, or whenever a new instance of WHISPers is deployed, the lookup tables will be automatically populated.

TODO
- [x] check how best to set password for admin user
- [x] Country - [USA is looked up by abbreviation](https://github.com/USGS-WiM/whispersservices/blob/dev/whispersapi/serializers.py#L2267)
- [x] Organization
- [x] EventType
- [x] CommentType

**Comment by machristie** [comment]
Hi @nbaertlein , here's the issue for documenting lookup tables. Can you  add the database tables that you know of that contain lookup values? Thanks.

**Comment by nbaertlein** [comment]
@machristie Attached are the lookup tables that I think will matter.  Hopefully this helps.  Please let me know if you need additional information. thanks.

[WHISPers_lookups_20200911.xlsx](https://github.com/USGS-WiM/whispersservices_django/files/5211484/WHISPers_lookups_20200911.xlsx)

**Comment by machristie** [comment]
Another option may be to create a fixture file (https://docs.djangoproject.com/en/3.1/howto/initial-data/#providing-data-with-fixtures). This could be exported from the production database.

**Comment by machristie** [comment]
Thinking a bit more about the fixture approach, I think it would be better to use a data migration for these key lookup tables where their special values are referenced and assumed to exist in the code. The fixture file approach might be good through for populating tables with some test data. For example, the whispers_organization record with id=1 (Public) has a special use in the code (default organization for new users), so it should be added if it doesn't exist via a data migration. But the other organizations might be exported into a fixture file and could be loaded for doing local testing, for example to test how the UI handles longer and shorter organization names, etc.

**Comment by machristie** [comment]
I created a draft PR #417 that adds a data migration for creating an admin user and the roles, but only if they are missing. Any feedback is appreciated.

I'll keep adding to this data migration with other lookup tables, like EventType, CommentType, Organization, etc.

**Comment by machristie** [comment]
Note to self: I might want to reorder this data migration to come before the 0054 migration in #404 since that one creates a NotificationMessageTemplate with the admin user (pk=1) as the created_by/modified_by user.

**Comment by machristie** [comment]
For creating the password for the admin user, I have the data migration create a random password and print to the console, with instructions on how to reset the password

Example migration output:
```
  Applying whispersapi.0055_auto_20201103_0845...Created admin user with password 'WtyhqKhKtB' - use 'python manage.py changepassword admin' to change the password
 OK
```

The roles are also automatically created and the admin user is given the SuperAdmin role. With this I'm able to run `python manage.py migrate` on a new database and then successfully login as the automatically created admin user.
