### ISSUE TITLE
Lost field in most recent services deployed

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#408]
Neil noticed a species diagnosis was not showing in the test env on the new VM, but still was on the old VM test env. I looked into it and determined that the `diagnosis_string` field was dropped.  See image below for comparo. Same event, same location species and diagnosis. The only difference is which server they are coming from (and presumably, code version)

![image](https://user-images.githubusercontent.com/6978380/96187016-e669a800-0f01-11eb-958c-e8208ffd6844.png)

Could there be any others like this that may have been dropped in the refactor maybe? Annoying question I know, but if you can identify a pattern we could avoid a fine-tooth-comb analysis to seek lost fields.

**Comment by aaronstephenson** [comment]
No pattern in the code really. But I'll look for all the *_string fields.

**Comment by aaronstephenson** [comment]
Ah, I see what happened. In the refactor the *_string fields are in the serializer `fields` list, but not declared. Easy to add back.

**Comment by aaronstephenson** [comment]
The only other missing one I found was 'cause_string' on SpeciesDiagnosis and SpeciesDiagnosisDetail serializers. Fixed in 2.0.2 06caf4ad.
