### ISSUE TITLE
No group ID showing in dashboard in whispersprod.cr

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices#412]
No group ID showing in dashboard tab  .

![image](https://user-images.githubusercontent.com/38669574/96274846-9c7ed180-0f96-11eb-924d-8fe89de908fa.png)

**Comment by BlakeDraper** [comment]
The `name` field, and a few other fields (namely  the '_string' ones) got dropped from the `/eventgroups` response. In the context above, 'ID' = `name` in the table and desired endpoint response.

**Comment by aaronstephenson** [comment]
Fixed in 2.0.4 5367c2a
