### ISSUE TITLE
Test site error on load

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices#415]
Get this when it's trying to load home page data:
![image](https://user-images.githubusercontent.com/38669574/97304967-7c6ad000-182a-11eb-9c9b-bc0fcfe24ede.png)

Get this when I try to log in:
![image](https://user-images.githubusercontent.com/38669574/97304991-84c30b00-182a-11eb-9eaf-6ff510846fa0.png)

**Comment by BlakeDraper** [comment]
@nbaertlein Its fixed. sorry - that was 100% my fault for not updating the reference to the correct URL when we made the change.
