### ISSUE TITLE
contacts/user_contacts response should not include records where active = false

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#430]
Need to reestablish this rule in the contacts response.

**Comment by aaronstephenson** [comment]
Yep, this ability was lost with the implementation of the django_filter package. I will figure out a way to make it work.

**Comment by aaronstephenson** [comment]
Fixed deployed in test environment.

**Comment by aaronstephenson** [comment]
Fix deployed in production environment.
