### ISSUE TITLE
Null start date on legacy events

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices#474]
I can't remember if we had this addressed in earlier versions...

Most legacy events (whispers_event.id < 200000), have start and end dates at the event level, but do not have dates at the location level.  Because of this, any update that is made (like toggling from 'complete' to 'incomplete') the standard date business rules are applied and overwrite the valid event dates with the null location dates.  To maintain our legacy data, we'd like to keep the event level dates if there are no location dates.

If this is a reversion in code, perhaps we can restore that caveat.  If new code is needed, lets discuss.  In the meantime, I've instructed our staff to avoid updating legacy events (only NWHC can change these), will populate the history tables with legacy data, and eventually populate null location dates with the event dates for single location events.

**Comment by BlakeDraper** [comment]
@aaronstephenson and @nbaertlein This would be in Aaron's court, but it feels like we need to discuss. Since event start date /end date is calculated and not directly entered, the business rule truly 'rules' these data fields. Without some way to indicate that an event is a legacy event (which does not currently exist in the data model) - there is no way to objectively apply this. You could have a rule that says 'do not delete any existing event start date /end date - only allow updates with a new value. But then you would not be able to clear/null out event dates without manual intervention from the data manager.

**Comment by nbaertlein** [comment]
Given then limited amount of time, I'd only recommend if it were reversion in existing code, or if it were a super easy fix.  

I agree arbitrary assignment of legacy event is not the best (id < 200000 or create date < -'2019-xx-xx').  I think a relatively easy fix for event start is that it could not be replaced with a null value.  Unfortunately, this is not so straight forward with end date as an existing event end date could be replaced with null, as would be the case if a new event location was added and the end was not known.    The only other option that I can think of is that neither the event start or the end date can be updated if any location has a null start date.

**Comment by aaronstephenson** [comment]
@nbaertlein  As Blake says, this is just how it's always operated, following the business rules. We could easily add a "hidden" field to the event table (perhaps named "legacy", type Boolean) that no one except the DBA and the API programmer would ever see (in other words, it would not be included in the serializer and therefore never exposed as JSON), and use that when applying business rules (which we would slightly modified to account for this situation). Neil, you as the DBA could then do a one-type table update to set this "legacy" field to true for the legacy events. This would only take an hour or two of my time.

Just a side note: there was no "reversion" of code, I don't know where this idea came from. We don't deliberately revert our code to a previous state unless there's an exceptional circumstance. There have been occasions where a bug fix inadvertently introduced another bug, but that's not a code reversion. We never intentionally circumvent business rules. Unfortunately, we just didn't have the budget to write unit tests that would protect against these introduced bugs, but perhaps that's something to include in a future budget.

**Comment by nbaertlein** [comment]
Ok. Let's leave as is.  We hope to update these events in the future so I don't want to spend the time on a work around.  
As for the 'reversion', that came from me.  I couldn't remember if we had discussed a while back (like years back) and had addressed it.  Thanks for clearing that up.  So many things to remember .... :P
