### ISSUE TITLE
Add field species_most_affected field to the eventsummary endpoint response

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#489]
This field will need to calculate which species within the event has the most individuals affected. In other words, it will need to add up the cumulative affected count for each locationspecies, compare across the whole event, and provide the species with the highest total affected count (ideally the whole species object, but can also work with just the species ID if necessary).

Background: the report currently calculates "Species Most Affected" by counting the total _instances_ in which that species appears, which is misleading. Meaning: white-tailed deer may be present at 5 different event locations, with one dead each, where brown bat appears at only 2 event locations, but with 300 dead at each. Brown Bat is the most affected, obviously, but the current count method would say the deer. I cannot calculate the actual cumulative count on the client with this summary response, because the needed data detail is not there. Therefore kicking it to the server.

**Comment by aaronstephenson** [comment]
Would this field be available to the public, or just to the owner + org + collab, or just admins?

**Comment by BlakeDraper** [comment]
Available to public

**Comment by aaronstephenson** [comment]
Field added in 30225b8 and deployed to the test environment.

**Comment by BlakeDraper** [comment]
Hold off on promoting this to prod. See (https://github.com/USGS-WiM/whispers/issues/1197) for details.

**Comment by aaronstephenson** [comment]
Removed in e93568f.
