### ISSUE TITLE
Event Detail reports not generating for all roles

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#499]
**Describe the bug**
For some roles (e.g., partner admin, partner manager, partner user), the event details report doesn't generate. First heard about this bug from Nancy Businga (partner admin) on live site; she has generated lots of event detail reports in the past and all was working ok for her previously. After hearing from Nancy, I then tested on test site with jennypartner1 (partner manager) and abilenetest (partner user) and could reproduce. 

To reproduce: log in as a partner, go to an event details page, click on "Generate Report", and blue bar on popup just keeps scrolling and scrolling.

![image](https://user-images.githubusercontent.com/49287076/124968090-d4c5b480-dfea-11eb-8f45-170afc51610d.png)

Same bug on Chrome, Firefox, and Edge.

Works fine from my jchipault (WHISPers admin) account and also works fine when not logged in at all. Have not tried other logged in account permissions other than those described above (i.e., haven't tried roles 6 and 7; short on time today)

Summary report on home page seems to work fine for all log ins I tried.

**Comment by aaronstephenson** [comment]
@JChipault This bug fix is now pushed to the test environment. Give it a try and let me know how it goes for you.

**Comment by JChipault** [comment]
Just testing now because I was on leave. Looks good!

**Comment by JChipault** [comment]
@aaronstephenson Can you let me know when it hits the live site so that I can let our partner know that it's fixed?

**Comment by aaronstephenson** [comment]
Fixed in v2.1.6 78c69f0 and pushed to the production environment.
