### ISSUE TITLE
redirect www.whispers.usgs.gov to whispers.usgs.gov

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#503]
We want to use whispers.usgs.gov as the url that we publish in outreach materials but if someone tries to type in www.whispers.usgs.gov, they get some version of this:

![image](https://user-images.githubusercontent.com/49287076/127536265-b0dd5434-5318-4115-ad63-01d388f0f33c.png)

This issue might come into play if, say, a partner is looking at an email with outreach material on their phone and they want to navigate to the website on their laptop so they manually type in a web address (which some of us who are old school still think always start with "www").

Can we set www.whispers.usgs.gov to redirect automatically to whispers.usgs.gov?

**Comment by aaronstephenson** [comment]
This is a back-end issue, so I transferred it. I wrote a rewrite rule in the Apache config to handle this, but then I remembered that the EROS WAF is involved, and so all requests to www.* are getting dropped there (because there is no matching server for that subdomain in their rules). I will email our new EROS contact to request that they add the www.* subdomains to their WAF rules so that my Apache redirects can work.

**Comment by aaronstephenson** [comment]
Our EROS contact says that their WAF has been updated for the www.* subdomains, but that we need to request the USGS DNS team create new DNS records and point them at the EROS WAF. It slipped my mind that our SSL certs don't cover subdomains that deep (for example, WHISPers prod uses the general usgs.gov wildcard, which allows whispers.usgs.gov but not www.whispers.usgs.gov).

**Comment by JChipault** [comment]
@aaronstephenson  Is there anything we need to do for this or is the above notes to yourself? (Sorry, I don't know the lingo).

**Comment by aaronstephenson** [comment]
Just progress updates, for documentation purposes. No tasks for you.

**Comment by aaronstephenson** [comment]
Here's what the USGS DNS folks replied:

>The *.usgs.gov wildcard SSL Cert does not cover subdomains, so your group would be on the hook for the purchase and annual renewal of a separate SSL Cert for that www domain name. I try to discourage www prefixes on USGS web sites but will grant the request if your team feels strongly about it. The Cert would still be needed, even for just redirection.

What would you like to do?

**Comment by aaronstephenson** [comment]
@nbaertlein @JChipault ☝️ 

Sorry, I should have "@-ed" you yesterday.

**Comment by JChipault** [comment]
@aaronstephenson  I sent it to Neil yesterday and he and Ali are contemplating. Thanks!

**Comment by JChipault** [comment]
@aaronstephenson We decided to put this on hold. If we start getting feedback that users are running into the issue of finding the site based on not having this redirect, we now know that our next step will be to purchase SSL cert, so thanks for that info!
