### ISSUE TITLE
standard notifications not issued

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#534]
I updated the following events on Sunday from roughly 6:15p to 8p Central: 201213, 201215, 201373, 201400, 201504

No notifications were generated or emailed for these events on Mon morning. 

Here's my standard notifications set up:
![image](https://user-images.githubusercontent.com/49287076/149998932-cf11d6ef-f6a7-4ac4-8c39-c9e9e7994e40.png)

I don't have any custom notifications on so can't assess those.

**Comment by JChipault** [comment]
Neil is thinking that this isn't related to #524 because my changes on Sunday weren't quite late enough in the evening

**Comment by JChipault** [comment]
Happened again. Last night (Monday night) at 6:35p C I updated 201329. I still have the notification settings in the screenshot above. I received multiple All Event and Your Organization Event notifications overnight but nothing for 201329.

**Comment by aaronstephenson** [comment]
Thanks @JChipault, I'll investigate right away. It's easier to troubleshoot immediately after something goes wrong, before much data is changed.

**Comment by aaronstephenson** [comment]
@JChipault so both of these happened because the changes happened after 6pm CST (midnight UTC). No one gave me the green light to deploy the fix I made [here](https://github.com/USGS-WiM/whispersservices/issues/524#issuecomment-999938624), which would have prevented these issues. How would you like to proceed?

**Comment by aaronstephenson** [comment]
Fix deployed in test and production environments as v2.1.11 0e85d7f
