### ISSUE TITLE
Implement Banner model and endpoint

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/whispersservices#546]
Intended for use as a HTML banner div in the main WHISPers client.

Fields:
- content (text)
- active (Boolean)
- end_date (date)
- type? (unsure if this is needed)

Admins can see all banners (or filter on the active field), while everyone else only sees active banners.

**Comment by aaronstephenson** [comment]
Initial work in new branch [546](https://github.com/USGS-WiM/whispersservices/tree/546) (commit 064e985f)

**Comment by aaronstephenson** [comment]
@BlakeDraper where did things end up with the proposed banner feature? Should I merge this into the test branch?

**Comment by BlakeDraper** [comment]
@aaronstephenson banner is on hold - no merge.
