### ISSUE TITLE
no emailed notifications for service response

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#553]
**Describe the bug**
It appears that real-time emails are being sent for service request comments but not for service request responses. We've tested this on the test site and also asked folks using the production site if they are getting emailed notifications for service request response and they say they are not. 

**To Reproduce**
1. From one user account put in a service request
2. From a different user account with WHISPers admin privileges, select a response to that service request (note that this is separate from making a comment... there's a "Respond" button that presents a yes/no/maybe option)
3. See if user account from step 1 gets an email
4. Note that no email is sent; however user from step 1 does get a notification in their user dashboard.

**Expected behavior**
Expect real-time service request response notification emailed out (in addition to being on user dashboard)

**Comment by JChipault** [comment]
well, that was fast! Thanks

**Comment by aaronstephenson** [comment]
You betcha! I just happened to be working on an other issue and this was an easy fix 😄

**Comment by JChipault** [comment]
Emails seem to be sending now. @nbaertlein - when Aaron pushes these fixes to the live site, it might be good to let epis know that they'll be getting these notifications now.
