### ISSUE TITLE
Append "role_string" to the /auth response

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#568]
Now this probably actually means appending "role_string" to the user object since that appears to be what comes back from the `auth` endpoint success. The reason for doing this is to allow us to hide the roles table from the API. The client is using it in one superficial way which could be circumvented by this small tweak. 

Let me know when done and I can update the client accordingly.

**Comment by aaronstephenson** [comment]
Hi Blake. When is this needed? I'm trying to finish a sprint on another project, so if this could wait until the middle of next week that would be fantastic.

**Comment by BlakeDraper** [comment]
@aaronstephenson sorry I missed your comment at the time. Obviously it has not been terribly urgent - but if you can do it in the next couple weeks (ideally before 2 weeks from today) that would be awesome.

**Comment by aaronstephenson** [comment]
The field is added. I made a [pull request](#569 ) in case Lauren or you want to review it, but it's only three changed lines and I could just merge it into the dev branch at any time.

**Comment by aaronstephenson** [comment]
Lauren reviewed and approved the pull request.

**Comment by aaronstephenson** [comment]
Also removed the Role endpoint (#570, #571).
